from typing import Any, Union, NewType, List, Iterator
from numpy import ndarray, dtype

ros_PointField = NewType("sensor_msgs.PointField", object)

class PointField:
    def __init__(self, data: ros_PointField = None) -> None: ...
    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, value: str) -> None: ...
    @property
    def count(self) -> str: ...
    @count.setter
    def count(self, value: int) -> None: ...
    @property
    def offset(self) -> str: ...
    @offset.setter
    def offset(self, value: int) -> None: ...
    @property
    def datatype(self) -> int: ...
    @datatype.setter
    def datatype(self, value: int) -> None: ...
    @property
    def npdesc(self) -> str: ...
    def __repr__(self) -> str: ...
    def to_msg(self) -> ros_PointField: ...
