from typing import Type
from pcl.PointCloud import PointCloud

def load_pcd(path: str) -> PointCloud: ...
def save_pcd(path: str, cloud: PointCloud, binary: bool = False): ...
def load_ply(path: str, return_type: Type): ...
def save_ply(path: str, cloud: PointCloud, binary: bool = False, use_camera: bool = False): ...
def save_bin(path: str, cloud: PointCloud): ...
